### ISSUE TITLE
maybe a bug in preprocessing step?

### ISSUE THREAD

**Issue by Mrswolf** [tiehangd/MUPS#1]
Hi, I am reading your paper and codes.  It looks like that you repeatedly add the same trial in **data_preprocessing.py**. 
```
        for ii in range(0,a_data.size):
            a_data1 = a_data[0,ii]
            a_data2=[a_data1[0,0]]
            a_data3=a_data2[0]
            a_X         = a_data3[0]
            a_trial     = a_data3[1]
            a_y         = a_data3[2]
            a_fs         = a_data3[3]
            a_classes     = a_data3[4]
            a_artifacts = a_data3[5]
            a_gender     = a_data3[6]
            a_age         = a_data3[7]
            for trial in range(0,a_trial.size):
                if(a_artifacts[trial]==0):
                    data_return[NO_valid_trial,:,:] = np.transpose(a_X[int(a_trial[trial]):(int(a_trial[trial])+Window_Length),:22])
                    class_return[NO_valid_trial] = int(a_y[trial])
                    NO_valid_trial +=1
            data.append(data_return[0:NO_valid_trial,:,:])
            label.append(class_return[0:NO_valid_trial])
```
There is one more indent before append data_return to data list, the number of trials is far more beyond the actual number of trials (288*2). 
I haven't read all codes so I don't know whether it would affect your results.

**Comment by tiehangd** [comment]
Hi Mrswolf, thank you for your interest in the project and the question. This preprocessing script produces data for the cross subject setting. With a total of 9 subjects, 8 is for training and 1 for testing. The code block pasted above prepares data for A0\*T of one subject, then the code block following it prepares data for A0\*E, and the code beginning from line 83 use the data_gen function to generate data of 8 subjects for training and one for testing. Hope this answer helps!

**Comment by Mrswolf** [comment]
@tiehangd 
Thanks for answering, but that's not my point. With subject1 as a test subject, the number of total test trials should be 288*2. However, preprocessing code produces a testing set of shape (1927, 22,  1750).

The problem is line 
`data.append(data_return[0:NO_valid_trial,:,:])`.
This line should be out of the inner loop. The correct code is as follows:

```
        for ii in range(0,a_data.size):
            a_data1 = a_data[0,ii]
            a_data2=[a_data1[0,0]]
            a_data3=a_data2[0]
            a_X         = a_data3[0]
            a_trial     = a_data3[1]
            a_y         = a_data3[2]
            a_fs         = a_data3[3]
            a_classes     = a_data3[4]
            a_artifacts = a_data3[5]
            a_gender     = a_data3[6]
            a_age         = a_data3[7]
            for trial in range(0,a_trial.size):
                if(a_artifacts[trial]==0):
                    data_return[NO_valid_trial,:,:] = np.transpose(a_X[int(a_trial[trial]):(int(a_trial[trial])+Window_Length),:22])
                    class_return[NO_valid_trial] = int(a_y[trial])
                    NO_valid_trial +=1
        data.append(data_return[0:NO_valid_trial,:,:])
        label.append(class_return[0:NO_valid_trial])
```
If you want to put `data.append(data_return[0:NO_valid_trial,:,:])`. in the inner loop. It should  be indexed with last_NO_valid_trial:NO_valid_trial instead of 0:NO_valid_trial.
