### ISSUE TITLE
Maybe a bug in dataloader/data_preprocessing.py? the train data and test data you use are the same.

### ISSUE THREAD

**Issue by DLily0129** [tiehangd/MUPS#4]
Hi, I am very interested in your research direction and have done some related research. 

But I found a hidden bug in your code dataloader/data_preprocessing.py. In general, there is no problem with the logic of the code (that is, there is no problem with the processing logic in the Matlab environment, and I have also seen similar Matlab version codes), but in the language of Python, problems will occur. 

For two types of data: "*T.mat" for training and "*.E.mat" for testing, the same variable "data_return" is used in your code. You first assign training data(variable "a_X" transposed and intercepted) to variable "data_return" and append it to the "data" list. Then you assign testing data(variable "b_X" transposed and intercepted) to variable "data_return" and append it to the "data" list.

But please note that, in Python, the data stored in the list is the memory address corresponding to the data instead of the real data. Therefore, when the testing data(variable "b_X" transposed and intercepted) is assigned to the "data_return" variable, the training data which is appended to the "data" list previously will also change at the same time, because the training data saved before is just the address of the  "data_return" variable.

Below are the relevant variables that I have seen using the "debug" mode in Pycharm. The same data in the "data" list confirms what I said above. 

This is before the training data(transposed and intercepted variable "a_X" stored in variable "data_return") is appended to the "data" list.
![捕获](https://user-images.githubusercontent.com/24854274/117545179-415a1c80-b057-11eb-9073-ae7a6984a542.PNG)

This is after the training data(transposed and intercepted variable "a_X" stored in variable "data_return") is appended to the "data" list. The 0th dimension is different because it is intercepted by the variable "NO_valid_trial".
![捕获2](https://user-images.githubusercontent.com/24854274/117545313-c9402680-b057-11eb-83e6-804c8889a242.PNG)

This is to assign the testing data(transposed and intercepted variable "b_X") to the "data_return" variable, you can find that the 0th data element in the "data" list has also changed. 
![捕获3](https://user-images.githubusercontent.com/24854274/117561997-2aa2dc80-b0ce-11eb-90a6-b59b35018b94.PNG)

This is after appending the testing data(transposed and intercepted variable "b_X" stored in variable "data_return") to the "data" list, you can find that the training data is the same as the test data. 
![捕获4](https://user-images.githubusercontent.com/24854274/117562047-8f5e3700-b0ce-11eb-9673-30a2b1869169.PNG)

And this is the result of looping multiple times.
![捕获5](https://user-images.githubusercontent.com/24854274/117562056-9be28f80-b0ce-11eb-8e9c-ec64cf4869b2.PNG)

Therefore, the training data and test data you use are exactly the same. I think this may make the results of your paper no longer credible.

**Comment by sabinechen** [comment]
It is true that the data_return is overwritten, that means all the  data from A0*T.mat is overwritten, so this code only use half data to train or to test, the results of this code are still credible.

**Comment by tiehangd** [comment]
Hi DLily0129, thank you for the comment. Please note we are doing cross subject EEG classification here and we are combining some subjects' "T." and "E." data as training and use other subjects as testing, which means we are not adhereing to the denotation in its original dataset of "T." for training and "E." for testing.

**Comment by yaoming2017** [comment]
Thanks for the sharing of code! Indeed, I agree with the problem proposed by DLily0129, it means that every T. is overwrited by the corresponding E., thus the work just use E. to be the final training set, and the same data would appear double times. And it is possible to get same datas when select instances randomly.
