### ISSUE TITLE
A very serious problem in your code

### ISSUE THREAD

**Issue by lla0727** [tiehangd/MUPS#5]
Hello, I would like to ask that the test set in your code is divided into val_set and test_set. val_set is used for meta-validation, test_set is used for meta-test, and val_set is used for meta-test. But the problem is that when test_set does meta-test, it will also randomly split into shot and query, and it will also enter meta_forward2 for gradient update, so the number of samples you really use for testing is 0, that is, your code is randomly sampled and trained on the test set. This violates the principle that the test set is invisible, which is a very serious error.

**Comment by tiehangd** [comment]
Thank you for the comment. The testing follows the same procedure as meta transfer learning. This repository is published 4 years ago and is not under active maintenance.
